### ISSUE TITLE
ETL: Add agolutil to atd-vz-data container

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#520]
@mateoclarke  and I had been struggling to install `atd-agol-util` into the container, the error shows as "Failed to cpythonize".

- [ ] Tried adding cpython
- [ ] Tried installing build-base  (to alpine linux)
- [ ] Tried installing numpy

No dice, atd-agol-util otherwise installs fine in my computer, maybe time to test with other distros.

**Comment by johnclary** [comment]
@sergiogcx weird. let me know if i can help. i assume the install issues come from the `arcgis` library dependencies. most of that libraries methods can be replaced with calls to the ArcREST API.

**Comment by sergiogcx** [comment]
It looks like it is trying to cythonize numpy:

```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_sfc64.pyx
    Traceback (most recent call last):
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/tools/cythonize.py", line 61, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/tools/cythonize.py", line 238, in <module>
        main()
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/tools/cythonize.py", line 66, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Cythonizing sources
    Running from numpy source directory.
    /tmp/easy_install-58tb56oy/numpy-1.18.0rc1/setup.py:425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/setup.py", line 450, in <module>

      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/setup.py", line 433, in setup_package
        def finalize_options(self):
      File "/tmp/easy_install-58tb56oy/numpy-1.18.0rc1/setup.py", line 240, in generate_cython
        """Custom distutils command to clean the .so and .pyc files."""
    RuntimeError: Running cythonize failed!
```

**Comment by sergiogcx** [comment]
So a few discoveries from yesterday:

I've managed to add `atd-agol-util` to the container, but it bloats the container from 500mb to 1.4gb, since alpine needs the compiler, a bunch of development libraries, utilities and dependencies (png, freetype, ssl, blas, zeromq, etc).

I can try working on reducing the size of the image, maybe using another distro with pre-compiled python libraries.

**Comment by sergiogcx** [comment]
Trying debian buster slim, on the very first layer installing chrome and chrome driver:

![2019-12-17_12-06-27.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7248a31f-9700-4519-8a24-065845b600db)

**Comment by sergiogcx** [comment]
Building the same container with debian buster-slim goes down to 1.29gb (we only save 100mb).

I also tried just building a separate container for atd-agol-util using buster-slim, and that seems to add up to 600mb, that with the existing etl image of 500mb adds up to 1.1gb (give or take).

**Comment by sergiogcx** [comment]
Multi-stage takes about 1gb and it takes forever to build:

![2019-12-17_15-25-31.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/9a84eefa-08a5-4c90-b76a-73b377a590cc)

**Comment by sergiogcx** [comment]
Based on this info, I think it is best to use separate docker containers. They build a lot faster, and they are easier to maintain.

**Comment by sergiogcx** [comment]
This is ready, added circleci build steps, updated runetl:

https://github.com/cityofaustin/atd-vz-data/pull/527
